Windows build support
katyo/aubio-rs pull request #9
Opened 2020-06-12 22:49 UTC by kukuen

Hi, I made the windows build working with MSVC.

For that I used the 0.4.9 release package from aubio and bundled WAF 2.0.20 with this patch manually applied : https://gitlab.com/ita1024/waf/-/commit/13d9c8566cb938cec12fab3cf731409366dbf8f7 (it's on the 2.1 branch and haven't been released yet)

2020-06-14 17:26 UTC, katyo commented
@kukuen Looks interesting... Thank you so much

2020-06-15 19:43 UTC, kukuen commented
@katyo Sure ! I could fork WAF and fetch an artifact from there. Would that be ok ?

2020-06-15 20:37 UTC, katyo commented
@kukuen, okay.

2020-06-17 05:02 UTC, katyo requested changes
looks good to me, but it will be better to merge commits to single one before merging this PR with master.

2020-06-17 05:02 UTC, katyo commented on aubio-lib/build.rs
> +        pub const URL: &str = "https://github.com/kukuen/waf/releases/download/2.0.20-msvc-fix/waf-light-{version}.tar.gz";
You can parameterize `URL` string with `{version}` and `{package}`:
```rust
pub const URL: &str = "https://github.com/kukuen/{package}/releases/download/{version}/waf-light-{version}.tar.gz";
```

2020-06-17 06:56 UTC, kukuen commented on aubio-lib/build.rs
> +        pub const URL: &str = "https://github.com/kukuen/waf/releases/download/2.0.20-msvc-fix/waf-light-{version}.tar.gz";
I made the changes, it should be good now :)

2020-06-17 08:23 UTC, merged